language: python

python:
    - 3.3
    - 3.4

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get install -qq wget python3-dev build-essential
    - sudo apt-get install -qq python3-pyqt4 libqt4-dev python3-sip-dev
    - cd /tmp
    - wget --quiet http://downloads.sourceforge.net/project/pyqt/sip/sip-4.16.6/sip-4.16.6.tar.gz
    - tar -xf sip-4.16.6.tar.gz
    - cd sip-4.16.6
    - python -B configure.py
    - make --quiet
    - sudo make --quiet install
    - cd /tmp
    - wget --quiet http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz
    - tar -xf PyQt-x11-gpl-4.11.3.tar.gz
    - cd PyQt-x11-gpl-4.11.3
    - python -B configure.py --confirm-license
    - make --quiet
    - sudo make --quiet install
    - sudo apt-get installpython-qscintilla2
    - cd $TRAVIS_BUILD_DIR

install:
    - pip install nose

script:
    - nosetests
