# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 1 # pagination based on number of posts
paginate_path: "page:num"
#exclude: [""] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Edis

description: a simple cross-platform IDE for C
author:
  name: Edis
  email: acostadariogabriel@gmail.com
  github: centaurialpha
  twitter: _alfacentauri
  #pinterest: asd123
  #linkedin: asd123
  bio: Edis - a simple cross-platform IDE for C
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: descargas.html
tags_path: acerca.html

BASE_PATH:
